name: Publish Release
on:
  workflow_dispatch:
    inputs:
      version:
        required: true
        description: Version
      changelog:
        required: true
        description: Changelog for new release
jobs:
  publish-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 21

      - name: Setup Gradle Caches
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: ${{ runner.os }}-gradle

      - name: Setup Gradle Wrapper
        run: chmod +x gradlew

      - name: Get Version and Platform
        id: properties
        uses: christian-draeger/read-properties@1.1.1
        with:
          path: "./gradle.properties"
          properties: "enabledPlatforms minecraftVersion"

      - name: Publish Release
        run: ./gradlew publish
        env:
          VERSION: ${{ github.event.inputs.version }}
          MAVEN_USER: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_PASS: ${{ secrets.MAVEN_PASSWORD }}

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ./neoforge/build/libs/!(*-@(dev|sources|dev-shadow)).jar
            ./fabric/build/libs/!(*-@(dev|sources|dev-shadow)).jar
            ./common/build/libs/!(*-@(dev|sources|dev-shadow)).jar

      - name: Generate Discord Embed
        run: ./gradlew injectEmbed
        with:
          VERSION: ${{ github.event.inputs.version }}
          CHANGELOG: ${{ github.event.inputs.changelog }}

      - name: Upload Discord Embed
        uses: tsickert/discord-webhook@v5.3.0
        with:
          webhook-url: ${{ secrets.WEBHOOK_URL }}
          raw-data: ./build/embed.json
